app = "casa-cre-review-template"
primary_region = "iad"

[build]
  dockerfile = "server/Dockerfile"

[deploy]
  release_command = "node_modules/.bin/prisma migrate deploy --schema=./prisma/schema.prisma && node_modules/.bin/tsx server/prisma/seed.ts"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
