name: deploy staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: deploy-staging
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    name: deploy casa-cre-develop
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only --config fly.toml --app casa-cre-develop
